spring:
  application:
    name: dubbo-auto-configuration-provider-demo

server:
  port: 8088

#system:
#  user:
#    name: zjhuang
#    password: 123456
#    age: 25

#dubbo:
#  scan:
#    base-packages: com.example.will.demo
#  application:
#    name: dubbo-auto-configuration-provider-demo
#  registry:
##      address: nacos://127.0.0.1:8848
#      address: N/A
#  protocols:
#    dubbo:
#      name: dubbo
#      port: 8083
#    rest:
#      name: rest
#      port: 8888
#    hessian:
#      name: hessian
#      port: 8084

